env:
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:import/recommended
  - prettier

parser: @babel/eslint-parser

rules:
  import/order:
    - error
    - alphabetize:
        order: 'asc'

  max-len:
    - error
    - 80
    - 2
    - ignoreUrls: true
      ignoreComments: false
      ignoreRegExpLiterals: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
